name: food_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  widgetbook_annotation: ^2.1.0
  intl: ^0.17.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_gen_runner: ^4.2.1+1
  flutter_lints: ^2.0.0
  widgetbook: ^2.3.0
  widgetbook_generator: ^2.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-SemiBold.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf

    - family: SF Compact
      fonts:
        - asset: assets/fonts/sf-compact-display-medium.otf
        - asset: assets/fonts/sf-compact-display-thin.otf

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
